Postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: 1234
  DBName: postgres
Server:
  Host: localhost
  Port: :50051
  Development: true 
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5
